---
language: python
python:
  - 3.7
  - 3.8
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip wheel
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - pylint freeswitch_exporter
  - pyflakes src/freeswitch_exporter
